### ISSUE TITLE
Typos (french)

### ISSUE THREAD

**Issue by f6fvy** [cozy-labs/import-from-google#11]
"Puis, copiez-collez le code affiché dans la fenêtre dans ce **champ** : "
"L’import de vos **calendriers** s’est parfaitement déroulé !"
"Félicitations, toutes vos données ont été **importées** avec succès..."

**Comment by cylwin** [comment]
Merci !
https://github.com/cozy-labs/leave-google/commit/4b64cafc5ac2ac740cefad3208d2380dcf444ab3
