### ISSUE TITLE
Blank contacts created

### ISSUE THREAD

**Issue by nicofrand** [cozy-labs/import-from-google#23]
I only used import-from-google to create contacts in my cozy.
Once imported (713 contacts), I have 2 blank contacts on the top:

![import-blank-contacts](https://cloud.githubusercontent.com/assets/3419050/9602866/719b52ee-50ac-11e5-93bd-1fa754120489.png)

I'd prefer not to show the whole logs (since my contacts name are in it), please ask if you know where to look…

**Comment by ArchangeGabriel** [comment]
Are they really fully blank? Don’t you have those blank contacts in Google Contacts too? I’m also having 4 partially blank contacts personally, but they do exist in my Google account too.

**Comment by nicofrand** [comment]
I deleted everything and imported the contacts again, the issue seems to be
fixed.

Le dim. 15 nov. 2015 12:22, Bruno Pagani notifications@github.com a
écrit :
