### ISSUE TITLE
Import doesn't display

### ISSUE THREAD

**Issue by babolivier** [cozy-labs/import-from-google#35]
Disclaimer: I'm running the app on a Cozy installed with the Archlinux package. The issue may not come from Cozy (nor the app), but from the package's dependencies. I'm interested in both cases, as I can update them in the second one.

I have the application installed on my Cozy, at the latest version (or at least I think it is, I updated the app this morning). I followed the "set-up" steps (entering Google's pin and what I want to import), and once I click on the "Import" button, I'm stuck just like [here](https://cozy.brendanabolivier.com/public/files/files/fbee0864b52d81b82294d337282956f1/attach/cozy.png).

All of my contacts and photos have been successfully imported within my Cozy.

**Comment by clochix** [comment]
Hi @babolivier,
FTR, version 0.1.4 just got released a few hours ago, with a lot of fixes and enhancements.
Also, looks like you hit a problem with Socket.io. It's initialization request get a 400 error, could you have a look at the server logs to see what happened ?

**Comment by babolivier** [comment]
Hi @clochix,
If by "server logs" you mean the logs for home/DS/proxy, there doesn't seem to be any problem. Actually, the server displays the requests to /socket.io/\* as successful, while I keep getting an error in the browser's console.
I use the Import From Google v0.1.4, if that's what you mean by "FTR".

**Comment by clochix** [comment]
@babolivier it's probably related to #36, a fix should be published in a few hours

**Comment by babolivier** [comment]
@clochix Well, I updated the app this morning to v0.1.5 and it's displaying fine now! I guess you can close this issue :)

**Comment by clochix** [comment]
Thanks, I wasn't aware the fix was already published. Thanx !
