### ISSUE TITLE
ReferenceError: toto is not defined(…) 

### ISSUE THREAD

**Issue by Shuunen** [cozy-labs/import-from-google#37]
```
"ReferenceError: toto is not defined
    at HTMLDocument.<anonymous> (https://johndoe.cozycloud.cc/apps/import-from-google/javascripts/app.js:140:17)
```

French touch power :)

**Comment by clochix** [comment]
Thanks for reporting @Shuunen.
I'm ashamed, I introduced this bug intentionally to check if our error reporting process was working, and I forgot to remove it ☹
It has been fixed in #36, soon available on a Cozy near you ;-)

**Comment by frankrousseau** [comment]
@clochix The fix is already available.

**Comment by clochix** [comment]
Thanks @frankrousseau ☺
@Shuunen could you update the application and give it another try?

**Comment by Shuunen** [comment]
I did and it worked well :) Got my gmail, picasa, gcal & gcontacts nicely ! The only thing was some empty picasa album, it was not a big deal, I cleaned them in less than a minute

**Comment by clochix** [comment]
Thanx for your feedback!
