### ISSUE TITLE
[Bug] Contacts import have some issues

### ISSUE THREAD

**Issue by ArchangeGabriel** [cozy-labs/import-from-google#40]
Hi,

First, thank you for making this great stuff. I’ve imported my contacts using this, but I face several issues:
1. Groups (=Labels in Cozy) are not imported, which is very annoying. I have around 2500 contacts in ~50 groups (a lot of contacts being in more than one), and I can’t afford the time to relabel everyone.
2. Default field name for addresses (email+physical) are not translated. For instance, `Home` stays this way even if I’m using french. Maybe this is an issue for the contacts app though, please tell me if I need to report this over there.
3. Physical addresses are imported with all fields separated by comma, even if they are empty. For instance, I had:
- `,,1, Rue de Paris,Paris,,75000,France` because only Street, City, ZIP and Country were filled in Google
- `,,1, Rue de Paris Paris 75000 France,,,,` because this was a wrong entry in Google that had everything in Street

So, maybe empty field and the associated comma should not be added to the field on import. For the last example, I don’t expect you to fix it on import, but if you do by implementing some parsing together with https://github.com/cozy/cozy-contacts/issues/189, that would be wonderful. Speaking of that correlated issue, it might also change the way of importing addresses and make it a lot easier by just copying over the different fields in the detailed address view at Google to Cozy ones.

Finally, a way to remove the Google label created on import would be nice, but maybe that does already exists and I just wasn’t able to found it.

**Comment by ArchangeGabriel** [comment]
Note that 3. has been almost been fixed on the contacts app side (2.1.1). 1. and 2. are still valid though.

**Comment by clochix** [comment]
Thanks for your great feedback @ArchangeGabriel ☺
I opened a specific issue to add groups: #41

@m4dz what about the second point: should I open another issue here or in cozy/cozy-contacts ?

**Comment by m4dz** [comment]
Thanks again for your precious feedback @ArchangeGabriel :smile:!

For the second point, I'm aware about the translation of datapoints' labels. I'll try to do it this sprint, no need to create a specific issue in Contacts.

**Comment by clochix** [comment]
Thanks, so I'll close this one and keep #41 for the last point.
Thanks to both of you!

**Comment by ArchangeGabriel** [comment]
@clochix, @m4dz: you’re welcome! It’s a pleasure to help your guys build this great piece of software the way I can. ;)
