### ISSUE TITLE
Install is failing

### ISSUE THREAD

**Issue by ArchangeGabriel** [cozy-labs/import-from-google#42]
I had to uninstall this app because it hanged (without any useful log, all I can say is I checked everything except for GMail, and that does not happen when I select only contact, will try other selections soon) and I wasn’t able to kill it (stop/start restore the blocked state).

When trying to reinstall:

```
# cozy-monitor install import from-google
info - Install started for import-from-google...
error - An error occured:
error - Install failed for import-from-google.
[Error: Install home failed for import-from-google.
Default git repo https://github.com/cozy/cozy-import-from-google.git doesn't exist.
You can use option -r to use a specific repo.]
```

Indeed, it seems to have moved (or ever been) under cozy-labs/import-from-google.

**Comment by clochix** [comment]
Hi @ArchangeGabriel,

This app is now available in our app store, did you try to install it from the Web UI ?

From the command line, I guess the command should be `cozy-monitor install -r https://github.com/cozy-labs/import-from-google.git import-from-google`.

**Comment by ArchangeGabriel** [comment]
Yes, I tried from the web UI but it was taking too long.

And indeed, I used this fixed command line to install.

**Comment by clochix** [comment]
And did the install succeed?

**Comment by ArchangeGabriel** [comment]
With that way, yes (though it took a long time too, and there was a message about that in the terminal output, can get it again if you need).
